services:
  - type: web
    name: Alfanio
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.js
        name: Content-Type
        value: application/javascript
      - path: /*.css
        name: Content-Type
        value: text/css
      - path: /*.png
        name: Content-Type
        value: image/png
      - path: /*.jpg
        name: Content-Type
        value: image/jpeg
      - path: /*.svg
        name: Content-Type
        value: image/svg+xml
      - path: /*.webp
        name: Content-Type
        value: image/webp
      - path: /*.woff
        name: Content-Type
        value: font/woff
      - path: /*.woff2
        name: Content-Type
        value: font/woff2
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
      - type: proxy
        source: /api/*
        destination: https://alfanio-ltd.onrender.com/api/:splat
      - type: proxy
        source: /contact/*
        destination: https://alfanio-ltd.onrender.com/contact/:splat
      - type: proxy
        source: /brochure/*
        destination: https://alfanio-ltd.onrender.com/brochure/:splat
    autoDeploy: true

  - type: web
    name: Alfanio ltd
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: RENDER
        value: "true"
      - key: MONGODB_URI
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 465
      - key: EMAIL_SECURE
        value: true
      - key: EMAIL_FROM_NAME
        value: Alfanio India
      - key: CLIENT_URL
        value: https://alfanio.in
      - key: FRONTEND_URL
        value: https://alfanio.onrender.com
    healthCheckPath: /healthz
    autoDeploy: true
